name: 构建并发布

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: 获取依赖
        run: flutter pub get
      - name: 启用Windows支持
        run: flutter config --enable-windows-desktop
      - name: 构建Windows版本
        run: flutter build windows --release
      - name: 打包Windows应用
        run: |
          cd build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath ../../../../../智能点名表-Windows.zip
      - name: 上传Windows构建产物
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: 智能点名表-Windows.zip
          
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: 获取依赖
        run: flutter pub get
      
      # 设置Android签名
      - name: 设置签名密钥
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > upload-keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS || 'upload' }}" >> android/key.properties
          echo "storeFile=../upload-keystore.jks" >> android/key.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      
      - name: 构建APK
        run: flutter build apk --release
      - name: 构建AAB
        run: flutter build appbundle --release
      - name: 上传Android构建产物
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: 获取依赖
        run: flutter pub get
      - name: 构建Web版本
        run: flutter build web --release
      - name: 打包Web文件
        run: |
          cd build/web
          zip -r ../../智能点名表-Web.zip *
      - name: 上传Web构建产物
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: 智能点名表-Web.zip

  create-release:
    needs: [build-windows, build-android, build-web]
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v3
      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-build/智能点名表-Windows.zip
            android-build/app-release.apk
            android-build/app-release.aab
            web-build/智能点名表-Web.zip
          name: 智能点名表 ${{ github.ref_name }}
          body: |
            ## 智能点名表 ${{ github.ref_name }} 发布
            
            ### 下载链接
            
            - [Windows版本](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/智能点名表-Windows.zip)
            - [Android APK](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release.apk)
            - [Android App Bundle](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release.aab)
            - [Web版本](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/智能点名表-Web.zip)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}