name: 生成Android签名密钥

on:
  workflow_dispatch:
    inputs:
      keystore_password:
        description: '密钥库密码'
        required: true
      key_password:
        description: '密钥密码'
        required: true
      key_alias:
        description: '密钥别名'
        required: true
        default: 'upload'

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 生成密钥库
        run: |
          keytool -genkey -v -keystore upload-keystore.jks -alias ${{ github.event.inputs.key_alias }} \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=智能点名表, OU=YourCompany, O=YourOrganization, L=YourCity, S=YourState, C=CN" \
            -storepass ${{ github.event.inputs.keystore_password }} \
            -keypass ${{ github.event.inputs.key_password }}
            
      - name: 上传密钥库为Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-keystore
          path: upload-keystore.jks
          
      - name: 创建key.properties文件
        run: |
          echo "storePassword=${{ github.event.inputs.keystore_password }}" > android/key.properties
          echo "keyPassword=${{ github.event.inputs.key_password }}" >> android/key.properties
          echo "keyAlias=${{ github.event.inputs.key_alias }}" >> android/key.properties
          echo "storeFile=../upload-keystore.jks" >> android/key.properties
          
      - name: 上传key.properties为Artifact
        uses: actions/upload-artifact@v3
        with:
          name: key-properties
          path: android/key.properties
          
      - name: 设置指南
        run: |
          echo "::::: 重要说明 :::::"
          echo "请下载android-keystore和key-properties Artifacts"
          echo "将upload-keystore.jks放在项目根目录"
          echo "将key.properties放在android/目录下"
          echo "添加以下GitHub Secrets来设置CI/CD系统："
          echo "KEYSTORE_BASE64 - 用Base64编码的密钥库"
          echo "KEYSTORE_PASSWORD - 密钥库密码"
          echo "KEY_PASSWORD - 密钥密码"
          echo "KEY_ALIAS - 密钥别名"
          echo ""
          echo "可以用以下命令生成Base64编码的密钥库："
          echo "base64 upload-keystore.jks | tr -d '\n'" 